name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-debian:
    name: "Test on Debian Linux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - rye
          - cypress
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating Debian tests for '${{ matrix.features }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i debian --preserve-test-containers
  test-ubuntu:
    name: "Test on Ubuntu Linux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - rye
          - cypress
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating Debian tests for '${{ matrix.features }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ubuntu --preserve-test-containers

  test-arch:
    name: "Test on Arch Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test Arch Linux"
        run: |
          set -e
          devcontainer features test -i archlinux -f rye --preserve-test-containers
